spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
  #mssql-datasource:
  #  jdbc-url:
  #  username:
  #  password:
  #  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

